config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  post '' => 'users#delete'
  get  'index' => 'users#index'
  post 'index' => 'users#create'
  get 'index/write' => 'users#write_excel'
  get 'index/single' => 'users#write_single'
  get  'show'  => 'users#show'
  get  'download' =>  'users#download'
  get  'comments' =>  'comments#comments'
  get  'top-fans' => 'comments#topComments'
  get  'top-fans/comments' => 'comments#singleUserComments'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
    attr_accessor :code
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def comments
        @id=params[:id]
        @user = User.find_by_id(@id) 
        @posts = @user.posts
        @allUserComments = @user.comments   
        @allUserComments = @allUserComments.sort_by{|k| k[:score] }
        @allComments=Kaminari.paginate_array(@allUserComments).page(params[:page]).per(50)
    end
        
    def topComments #sort by number of times
        @id=params[:id]
        @type = params[:type]
        @user = User.find_by_id(@id) 
        @posts = @user.posts
        @comments = @user.comments.to_a
        @comments =@comments.sort_by{|k| k.username}
        t =1
        total = @comments[0].score
        list = []
        for i in 0..@comments.length-2
            if @comments[i].username == @comments[i+1].username
                t = t+1
                total = total + @comments[i+1].score
            else 
                list.push({username: @comments[i].username, comment_times: t, totalScore: total, score: total/t})
                t =1
                total = @comments[i+1].score
            end
        end
        list = list.reject {|k| k[:username] ==@user.username}
        @top_list =list.sort_by{|k| k[:comment_times]}
        @top_list = @top_list.last(50).reverse
        if @type == "highest"
            @top_list =list.sort_by{|k| k[:totalScore]}
            @top_list = @top_list.last(50).reverse
        end
        if @type == "lowest"
            @top_list =list.sort_by{|k| k[:totalScore]}
            @top_list = @top_list.first(50)
        end
    end
    def singleUserComments
        @id=params[:id]
        @username = params[:name]
        @user = User.find_by_id(@id) 
        @posts = @user.posts
        @comments = @user.comments.where('username=?', @username)
        #sort with drop down Average Score
        sort_type = params[:type]
        if (sort_type=="highest")
            @comments=@comments.sort_by {|u| u.score*-1}
        end
        if (sort_type=="lowest")
            @comments=@comments.sort_by {|u| u.score}
        end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/comments.html.erb
<style>
.pagination {
    margin: auto;
    margin-bottom: 10px;
    width: 40%;
    border: 1px solid grey;
    padding: 10px;
}
.pagination a {
    padding: 8px 16px;
}
</style>
<div class="row">
    <div class="col-lg-12">
      <h1 class="title text-center">Comments Statistics</h1>
      <table width="1000" align="center" class="text-left">
        <tr>
          <td><h5>Username:</h5><td>
          <td><h5> <%= @user.username%></h5><td>
        </tr>
        <tr>
          <td><h5>Number of Port:</h5><td>
          <td><h5> <%= @posts.length%></h5><td>
        </tr>
        <tr>
          <td><h5>From</h5><td>
          <td><h5><%=@posts[-1].date%></h5><td>
        </tr>
        <tr>
          <td><h5>To</h5><td>
          <td><h5><%=@posts[0].date%></h5><td>
        </tr>
        <tr>
          <td><h5>Total of Comments:</h5><td>
          <td><h5><%=@user.totalComment%></h5><td>
        </tr>
        <tr>
          <td><h5>Average Score:</h5><td>
          <td><h5><%=@user.averageScore%></h5><td>
        </tr>
         <tr>
          <td><h5>Highest Score:</h5><td>
          <td><h5><%=@user.highestScore%></h5><td>
        </tr>
        <tr>
          <td><h5>URL:</h5><td>
          <td><a href="<%=@user.highestUrl%>"><h5><%=@user.highestUrl%></h5></a><td>
        </tr>
         <tr>
          <td><h5>Lowest Score:</h5><td>
          <td><h5><%=@user.lowestScore%></h5><td>
        </tr>
        <tr>
          <td><h5>URL:</h5><td>
          <td><a href="<%=@user.lowestUrl%>"><h5><%=@user.lowestUrl%></h5></a><td>
        </tr>
      </table>
    </div>
    
    <table align="center">
          <td><%= link_to "<button class='btn btn-primary'>Download Basic Information</button>".html_safe, index_write_path(id: @id, type:"single") %><td>
          <td><%= link_to "<button class='btn btn-primary'>Download All Comments</button>".html_safe, index_write_path(id: @id, type:"all")  %><td>
          <td><%= link_to "<button class='btn btn-primary'>Download All Comments By Rank</button>".html_safe, index_write_path(id: @id, type:"rank") %><td>
    </table>
    <br></br>
    <div class="col-lg-12 form-group">
      <table class="table">
        <thead>
          <th>No</th>
          <th>Username</th>
          <th>Comments</th>
          <th>Score</th>
          <th>Post Date</th>
          <th>Link</th>
          <th>Image</th>
        </thead>
        <tbody>
         <% @allComments.each do |cm|%>
          <tr>
            <td><%=@allUserComments.index(cm)+1%></td>
            <td><b><%=cm.username %></b></td>
            <td><%=cm.body%></td>
            <td><%=cm.score%></td>
            <td width = "10%"><%=@posts.find_by_id(cm.post_id)['date']%></td>
            <td><%=link_to "#{@posts.find_by_id(cm.post_id)['link']}", @posts.find_by_id(cm.post_id)['link']%></td>
            <td><%=link_to image_tag(@posts.find_by_id(cm.post_id)['image'], height: '100', width: '100'), @posts.find_by_id(cm.post_id)['image'] %></td>
          </tr>  
        <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div>
      <%= paginate @allComments %>
  </div>

app/views/comments/singleUserComments.html.erb
    <div class="col-lg-12 form-group">
    <br>
    <h2 class="title text-center"> Username: <a href="https://www.instagram.com/<%=@username%>"><%=@username%></a></h2>
    <br>
      <table class="table">
        <thead>
          <th>No</th>
          <th>Comments</th>
          <th width = "10%"><div class="dropdown show">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Score
            </a>
            <div class="dropdown-menu"  aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="comments?id=<%=@id%>&name=<%=@username%>">Normal</a>
              <a class="dropdown-item" href="comments?id=<%=@id%>&name=<%=@username%>&type=highest">Highest Average</a>
              <a class="dropdown-item" href="comments?id=<%=@id%>&name=<%=@username%>&type=lowest">Lowest Average</a>
            </div>
          </div></th>
          <th>Post Date</th>
          <th>Link</th>
          <th>Image</th>
        </thead>
        <tbody>
         <% @comments.each do |cm|%>
          <tr>
            <td><%=@comments.index(cm)+1%></td>
            <td><%=cm.body%></td>
            <td><%=cm.score%></td>
            <td><%=@posts.find_by_id(cm.post_id)['date']%></td>
            <td><%=link_to "#{@posts.find_by_id(cm.post_id)['link']}", @posts.find_by_id(cm.post_id)['link']%></td>
            <td><%=link_to image_tag(@posts.find_by_id(cm.post_id)['image'], height: '100', width: '100'), @posts.find_by_id(cm.post_id)['image'] %></td>
          </tr>  
        <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/comments/topComments.html.erb
<div class="row">
    <div class="col-lg-12">
      <h1 class="title text-center">Comments Statistics</h1>
      <table width="1000" align="center" class="text-left">
        <tr>
          <td><h5>Username:</h5><td>
          <td><h5> <%= @user.username%></h5><td>
        </tr>
        <tr>
          <td><h5>Number of Port:</h5><td>
          <td><h5> <%= @posts.length%></h5><td>
        </tr>
        <tr>
          <td><h5>From</h5><td>
          <td><h5><%=@posts[-1].date%></h5><td>
        </tr>
        <tr>
          <td><h5>To</h5><td>
          <td><h5><%=@posts[0].date%></h5><td>
        </tr>
        <tr>
          <td><h5>Total of Comments:</h5><td>
          <td><h5><%=@user.totalComment%></h5><td>
        </tr>
        <tr>
          <td><h5>Average Score:</h5><td>
          <td><h5><%=@user.averageScore%></h5><td>
        </tr>
         <tr>
          <td><h5>Highest Score:</h5><td>
          <td><h5><%=@user.highestScore%></h5><td>
        </tr>
        <tr>
          <td><h5>URL:</h5><td>
          <td><a href="<%=@user.highestUrl%>"><h5><%=@user.highestUrl%></h5></a><td>
        </tr>
         <tr>
          <td><h5>Lowest Score:</h5><td>
          <td><h5><%=@user.lowestScore%></h5><td>
        </tr>
        <tr>
          <td><h5>URL:</h5><td>
          <td><a href="<%=@user.lowestUrl%>"><h5><%=@user.lowestUrl%></h5></a><td>
        </tr>
      </table>
    </div>
    
    <br></br>
    <div class="col-lg-12 form-group">
      <table class="table" >
        <thead>
          <th>No</th>
          <th>Username</th>
          <th>Comment Times</th>
           <th>Total Score</th>
          <th>Average Score</th>
        </thead>
        <tbody>
         <% @top_list.each do |cm|%>
          <tr>
            <td><%=@top_list.index(cm)+1%></td>
            <td><b><%=link_to "#{cm[:username]}", top_fans_comments_path(id: @id, name: cm[:username]) %></b></td>
            <td><%=cm[:comment_times]%></td>
            <td><%=cm[:totalScore].round(3)%></td>
            <td><%=cm[:score].round(3)%></td>
          </tr>  
        <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>