config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  post '' => 'users#delete'
  get  'index' => 'users#index'
  post 'index' => 'users#create'
  get 'index/write' => 'users#write_excel'
  get 'index/single' => 'users#write_single'
  get  'show'  => 'users#show'
  get  'download' =>  'users#download'
  get  'comments' =>  'comments#comments'
  get  'top-fans' => 'comments#topComments'
  get  'top-fans/comments' => 'comments#singleUserComments'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts, dependent: :destroy
    has_many :comments, through: :posts
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @users_all = User.all
        #search
        username = params[:username]
        if !username.nil?
        @users_all = @users_all.find_all{|w| w.username.include?(username)}
        end
        #sort search result
         url =  request.fullpath
         if url.include?('username')
             @urlNormal = "?utf8=✓&username=#{username}&commit=Search"
             @urlHighest ="?utf8=✓&username=#{username}&commit=Search&type=highest"
             @urlLowest = "?utf8=✓&username=#{username}&commit=Search&type=lowest"
         else
             @urlNormal = "/"
             @urlHighest = '?type=highest'
             @urlLowest =  '?type=lowest'
         end
        #sort with drop down Average Score
        sort_type = params[:type]
        if (sort_type=="highest")
            @users_all=@users_all.sort_by {|u| u.averageScore*-1}
        end
        if (sort_type=="lowest")
            @users_all=@users_all.sort_by {|u| u.averageScore}
        end
        # paging area
        @users=Kaminari.paginate_array(@users_all).page(params[:page]).per(10)
    end

    def index    
        @id=params[:id]
        sort_type = params[:type]
        @user = User.find_by_id(@id)
        @posts= @user.posts     
        if (sort_type=="highest")
            @posts =  @posts.sort_by {|p| p.averageScore*-1}
        end
        if (sort_type=="lowest")
            @posts =  @posts.sort_by {|p| p.averageScore}
        end
    end

    def show
       #get param
       @id=params[:id]
       @post_id=params[:post_id]
       @type=params[:type]
       #find user 
       @user=User.find_by_id(@id)
       @posts= @user.posts 
       @all_comments=@posts.find_by_id(@post_id).comments
       @comments=Kaminari.paginate_array(@all_comments).page(params[:page]).per(50)
       if @type=="rank"
           @all_comments= @all_comments.sort_by{|k| k[:score] }
           @comments=Kaminari.paginate_array(@all_comments).page(params[:page]).per(50)
       end
    end    
    
    def delete
        @id=params[:id]
        @user = User.find_by_id(@id)
        @user.destroy
        redirect_to root_path
    end
=begin
---------------------------------***********************--------------------------
    This area is the code for crawling data from instagram when clicking submit on homepage
---------------------------------***********************--------------------------
=end
def create
    flash.clear
    # kill other chrome process
    system("killall chrome")
    #declare dom of posts
    post_dom=[]
    #Get Instagram Url
    insta_url=params[:insta_url]
    #Get pass
    pass=params[:pass]
    #all comments
    allUserComments = []
    if pass=="parastar"
        #run chrome
        options = Selenium::WebDriver::Chrome::Options.new
        options.add_argument('--headless')
        options.add_argument('--no-sandbox')
        @@bot = Selenium::WebDriver.for :chrome, options: options
        #@@bot = Selenium::WebDriver.for :chrome
        @@bot.manage.window.maximize
        sleep 1
        @@bot.navigate.to "https://www.instagram.com/#{insta_url}"
        sleep 1  
        if @@bot.find_elements(:xpath, '/html/body/span/section/main/div/div/article/div/div/div/div').size >0 
            #get account_id
            user_id = @@bot.find_element(:xpath, '/html/body/span/section/main/div/header/section/div[1]/h1').text
            #Save Instagram account
            @user=User.new(username:  user_id)         
            #close login requirement 
            @@bot.find_element(:xpath, '/html/body/span/section/nav/div[2]/div/div/div[3]/div/div/section/div/button').click
            
            #scroll down the account page and save dom
            for i in 0..8
                @@bot.action.send_keys(:end).perform
                sleep 1
                #save dom after 8 times press page down button
                if i%4==0
                    # elements contain the content of a post
                    dom=@@bot.find_elements(:xpath, '/html/body/span/section/main/div/div/article/div/div/div/div')
                    for i in dom
                        if i.find_elements(:tag_name,'a').size>0
                            dom=[];
                            dom[0]=i.find_element(:tag_name,'a')['href']
                            dom[1]=i.find_element(:tag_name,'img')['src']
                            post_dom.push(dom) 
                        end   
                    end      
                end 
            end
            #avoid duplicate when save dom
            post_dom=post_dom.uniq
            #Get exactly 100 post
            post_dom=post_dom[0..99]
            k=0
            # Instantiates a client
            language = Google::Cloud::Language.new
            for i in 0..post_dom.length-1   
                @@bot.navigate.to "#{post_dom[i][0]}"
                #save like, image and date
                date = @@bot.find_element(:xpath, '/html/body/span/section/main/div/div/article/div[2]/div[2]/a/time')['title']
                @post=@user.posts.new(
                    link: post_dom[i][0],
                    image: post_dom[i][1],
                    date: date,
                    code: i
                )
                #set time to reload, change session
                start_time= Time.now
                while @@bot.find_elements(:xpath, '/html/body/span/section/main/div/div/article/div[2]/div[1]/ul/li[2]/button').size > 0 do
                    if @@bot.find_elements(:xpath, '/html/body/span/section/main/div/div/article/div[2]/div[1]/ul/li[2]/button[@disabled=""]').size > 0
                        sleep 3
                    else
                        @@bot.find_element(:xpath, '/html/body/span/section/main/div/div/article/div[2]/div[1]/ul/li[2]/button').click
                        sleep 0.5
                    end
                    if (Time.now > start_time + 60)
                        sleep 3 
                        if @@bot.find_elements(:xpath, '/html/body/span/section/main/div/div/article/div[2]/div[1]/ul/li[2]/button[@disabled=""]').size > 0                    
                            if k==0 
                                @@bot.quit()
                                options = Selenium::WebDriver::Chrome::Options.new
                                options.add_argument('--headless')
                                options.add_argument('--no-sandbox')
                                @@bot = Selenium::WebDriver.for :chrome, options: options
                                #@@bot = Selenium::WebDriver.for :chrome
                                @@bot.manage.window.maximize
                                @@bot.navigate.to "https://www.instagram.com/accounts/login/?force_classic_login"
                                sleep 0.5
                                #using username and password to login
                                @@bot.find_element(:id, 'id_username').send_keys 'minhho402'
                                @@bot.find_element(:id, 'id_password').send_keys '515173'
                                @@bot.find_element(:class, 'button-green').click
                                sleep 0.5
                                @@bot.navigate.to "#{post_dom[i][0]}"  
                                k=1
                                start_time= Time.now
                            else  
                                @@bot.quit()
                                options = Selenium::WebDriver::Chrome::Options.new
                                options.add_argument('--headless')
                                options.add_argument('--no-sandbox')
                                @@bot = Selenium::WebDriver.for :chrome, options: options
                                #@@bot = Selenium::WebDriver.for :chrome
                                @@bot.manage.window.maximize
                                @@bot.manage.window.maximize
                                @@bot.navigate.to "#{post_dom[i][0]}"
                                sleep 0.5
                                @@bot.find_element(:xpath, '/html/body/span/section/nav/div[2]/div/div/div[3]/div/div/section/div/button').click
                                k=0
                                start_time= Time.now
                            end
                        else
                            start_time= Time.now
                        end
                    end
                end
                    #find comments
                    dom_comment=@@bot.find_elements(:xpath, '/html/body/span/section/main/div/div/article/div[2]/div[1]/ul/li')
                    dom_comment.shift
                    #for solving unsupported languages
                    text = "아니요오 내일은 파이톤 제품은 할인이 없어요."
                    @username = []
                    for d in dom_comment
                        comment=d.find_element(:tag_name, 'span').text
                        comment=comment.gsub(/[!().~`,:;<>?|'"{}\\\/\[\]]/,' ')
                        comment=comment.gsub("\n",' ')
                        if comment[/\b[a-zA-Z0-9\p{Hangul}]+\b/].nil?
                            comment=comment[0..29]
                        end
                        if comment.scan(/[a-zA-Z ]/).size==1
                            comment.insert(0,"-")
                        end
                        #for sure each comment is each sentence
                        comment.insert(-1,".")
                        text << "\n"
                        text << "\n"
                        text << comment
                        @username.push(d.find_element(:tag_name, 'a')['title'])
                    end
                    # Detects the sentiment of the text
                    response = language.analyze_sentiment content: text, type: :PLAIN_TEXT
                    # Get document sentiment from response
                    sentences = response.sentences
                    sentences.shift

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/all_comments.html.erb
<style>
.pagination {
    margin: auto;
    margin-bottom: 10px;
    width: 40%;
    border: 1px solid grey;
    padding: 10px;
}
.pagination a {
    padding: 8px 16px;
}
</style>
<div class="row">
    <div class="col-lg-12">
      <h1 class="title text-center">Comments Statistics</h1>
      <table width="1000" align="center" class="text-left">
        <tr>
          <td><h5>Username:</h5><td>
          <td><h5> <%= @user.username%></h5><td>
        </tr>
        <tr>
          <td><h5>Number of Port:</h5><td>
          <td><h5> <%= @posts.length%></h5><td>
        </tr>
        <tr>
          <td><h5>From</h5><td>
          <td><h5><%=@posts[-1].date%></h5><td>
        </tr>
        <tr>
          <td><h5>To</h5><td>
          <td><h5><%=@posts[0].date%></h5><td>
        </tr>
        <tr>
          <td><h5>Total of Comments:</h5><td>
          <td><h5><%=@user.totalComment%></h5><td>
        </tr>
        <tr>
          <td><h5>Average Score:</h5><td>
          <td><h5><%=@user.averageScore%></h5><td>
        </tr>
         <tr>
          <td><h5>Highest Score:</h5><td>
          <td><h5><%=@user.highestScore%></h5><td>
        </tr>
        <tr>
          <td><h5>URL:</h5><td>
          <td><a href="<%=@user.highestUrl%>"><h5><%=@user.highestUrl%></h5></a><td>
        </tr>
         <tr>
          <td><h5>Lowest Score:</h5><td>
          <td><h5><%=@user.lowestScore%></h5><td>
        </tr>
        <tr>
          <td><h5>URL:</h5><td>
          <td><a href="<%=@user.lowestUrl%>"><h5><%=@user.lowestUrl%></h5></a><td>
        </tr>
      </table>
    </div>
    
    <table align="center">
          <td><%= link_to "<button class='btn btn-primary'>Download Basic Information</button>".html_safe, index_write_path(id: @id, type:"single") %><td>
          <td><%= link_to "<button class='btn btn-primary'>Download All Comments</button>".html_safe, index_write_path(id: @id, type:"all")  %><td>
          <td><%= link_to "<button class='btn btn-primary'>Download All Comments By Rank</button>".html_safe, index_write_path(id: @id, type:"rank") %><td>
    </table>
    <br></br>
    <div class="col-lg-12 form-group">
      <table class="table">
        <thead>
          <th>No</th>
          <th>Username</th>
          <th>Comments</th>
          <th>Score</th>
          <th>Link</th>
          <th>Image</th>
        </thead>
        <tbody>
         <% @allComments.each do |cm|%>
          <tr>
            <td><%=@allUserComments.index(cm)+1%></td>
            <td><b><%=cm.username %></b></td>
            <td><%=cm.body%></td>
            <td><%=cm.score%></td>
            <td><%=link_to "#{@posts.find_by_id(cm.post_id)['link']}", @posts.find_by_id(cm.post_id)['link']%></td>
            <td><%=link_to image_tag(@posts.find_by_id(cm.post_id)['image'], height: '100', width: '100'), @posts.find_by_id(cm.post_id)['image'] %></td>
          </tr>  
        <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div>
      <%= paginate @allComments %>
  </div>

app/views/users/index.html.erb
<div class="row">
    <div class="col-lg-12">
      <h1 class="title text-center">Comments Statistics</h1>
      <table width="1000" align="center" class="text-left">
        <tr>
          <td><h5>Username:</h5><td>
          <td><h5> <%= @user.username%></h5><td>
        </tr>
        <tr>
          <td><h5>Number of Port:</h5><td>
          <td><h5> <%= @posts.length%></h5><td>
        </tr>
        <tr>
          <td><h5>From</h5><td>
          <td><h5><%=@posts[-1].date%></h5><td>
        </tr>
        <tr>
          <td><h5>To</h5><td>
          <td><h5><%=@posts[0].date%></h5><td>
        </tr>
        <tr>
          <td><h5>Total of Comments:</h5><td>
          <td><h5><%=@user.totalComment%></h5><td>
        </tr>
        <tr>
          <td><h5>Average Score:</h5><td>
          <td><h5><%=@user.averageScore%></h5><td>
        </tr>
         <tr>
          <td><h5>Highest Score:</h5><td>
          <td><h5><%=@user.highestScore%></h5><td>
        </tr>
        <tr>
          <td><h5>URL:</h5><td>
          <td><a href="<%=@user.highestUrl%>"><h5><%=@user.highestUrl%></h5></a><td>
        </tr>
         <tr>
          <td><h5>Lowest Score:</h5><td>
          <td><h5><%=@user.lowestScore%></h5><td>
        </tr>
        <tr>
          <td><h5>URL:</h5><td>
          <td><a href="<%=@user.lowestUrl%>"><h5><%=@user.lowestUrl%></h5></a><td>
        </tr>
      </table>
    </div>
    
    <table align="center">
          <td><%= link_to "<button class='btn btn-primary'>Download Basic Information</button>".html_safe, index_write_path(id: @id, type:"single") %><td>
          <td><%= link_to "<button class='btn btn-primary'>Download All Comments</button>".html_safe, index_write_path(id: @id, type:"all")  %><td>
          <td><%= link_to "<button class='btn btn-primary'>Download All Comments By Rank</button>".html_safe, index_write_path(id: @id, type:"rank") %><td>
    </table>
    <br></br>
    <div class="col-lg-12 form-group">
      <table class="table">
        <thead>
          <th>No</th>
          <th>Image</th>
          <th>Post Date</th>
          <th>Link</th>
          <th>Comments</th>
          <th>Lowest</th>
          <th>Highest</th>
          <th>Average</th>
        </thead>
        <tbody>
        <% i=0%>  
         <% @posts.each do |post|%>
          <tr>
            <td><%=i+1%></td>
            <td><%=link_to image_tag(post.image, height: '100', width: '100'), post.image %></td>
            <td width = "10%"><%= post.date%></td>
            <td><%=link_to "#{post.link}", post.link%></td>
            <td><%= post.totalComments%></td>
            <td><%= post.minScore%></td>
            <td><%= post.maxScore%></td>
            <td><%= post.averageScore%></td>
            <td align = "center">
            <%= link_to "<button class='btn btn-link'>View as normal</button>".html_safe , show_path(id: @id, post_id: post.id,type: "normal") %>
            <%= link_to "<button class='btn btn-small'>Download</button>".html_safe, index_single_path(id: @id, post_id: post.id, type:"normal")%>
            </td> 
            <td>
            <%= link_to "<button class='btn btn-link'>View as rank</button>".html_safe , show_path(id: @id, post_id: post.id,type: "rank") %>   
            <%= link_to "<button class='btn btn-small'>Download</button>".html_safe, index_single_path(id: @id, post_id: post.id,type: "rank") %>
            </td>
            <%i=i+1%>
          </tr>  
        <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<style>
.pagination {
    margin-bottom: 10px;
    margin-top: 20px;
    margin-left: 50px;
    width: 40%;
    padding: 10px;
}
.pagination a {
    padding: 8px 16px;
}
</style>
<div class="container text-center">
    <div>
      <h2 class="title">Enter a Instagram Username</h2>
    </div>
    <div>
        <%= form_tag :action => "index" do %>
          <div class="form-group" >
            <%= text_field_tag :insta_url, nil, placeholder: 'Hint: hyejung_belle, katiejonesknit...', class: "col-lg-4" %>
          </div>
           <div class="form-group" >
            <%= password_field_tag :pass, nil, placeholder: 'Enter secret code...', class: "col-lg-2" %>
          </div>
          <div class="text-center">
            <%= submit_tag "Submit", class: "btn btn-info" %>
          </div>
          <% end %>
          
    </div>
</div>

<div class="container">
    <%= form_tag('/', :method => :get) do %>
      <table>
          <td style ="padding-right:15px;"> 
            <%= text_field_tag :username, params[:username], placeholder: 'Enter an ID', class: "col-lg-12" %>
          </td>
          <td>
            <%= submit_tag "Search", class: "btn btn-info"%>
          </td>
           <% end %>
      </table>
    <hr>
    <table width="100%">
      <thead>
        <th>Number</th>
        <th>Username</th>
        <th><div class="dropdown show">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuButton" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Average Score
            </a>
            <div class="dropdown-menu"  aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="<%= @urlNormal%>">Normal</a>
              <a class="dropdown-item" href="<%= @urlHighest%>">Highest Average</a>
              <a class="dropdown-item" href="<%= @urlLowest%>">Lowest Average</a>
            </div>
          </div></th>
        <th>Date Start</th>
        <th>Date End</th>
      </thead>
      <tbody>
          <% @users.each do |user|%>
            <tr>
              <td class="text-center"><%=@users.index(user)+1%></td>
              <td><b><%=link_to "#{user.username}", index_path(id: user.id) %></b></td>
              <td class="text-center" ><%=user.averageScore%></td>
              <td><%=user.posts[-1].date%></td>
              <td><%=user.posts[0].date%></td>
              <td><%= link_to "<button class='btn btn-info'>View Detail</button>".html_safe , index_path(id: user.id) %></td>
              <td><%= link_to "<button class='btn btn-info'>View all Comments</button>".html_safe , comments_path(id: user.id) %></td>
              <td style= "padding: 5px;"><%= button_to "Delete", root_path(id: user.id), data: {confirm: 'Are you sure to delete this account?'}, class:  'btn btn-danger'%></td>
            </tr>
              <%end%>
      </tbody>
    </table>
    <div>
      <%= paginate @users %>
  </div>
</div>

app/views/users/show.html.erb
<style>
.pagination {
    margin: auto;
    margin-bottom: 10px;
    width: 40%;
    border: 1px solid grey;
    padding: 10px;
}
.pagination a {
    padding: 8px 16px;
}
</style>
  <div class="row">
    <div class="col-lg-12 text-center">
      <h1 class="title">Comments</h1>
    </div>
    <div class="col-lg-12 form-group">
      <table class="table">
        <thead>
          <th>No</th>
          <th>Username</th>
          <th>Content</th>
          <th>Score</th>
        </thead>
        <tbody>
        <% @comments.each do |cm|%>  
          <tr>
          <td><%=@all_comments.index(cm)+1%></td>
            <td><b><%=cm.username%></b></td>
            <td><%=cm.body%></td>
            <td><%=cm.score%></td>
          </tr>
        <%end%>
        </tbody>
      </table>
    </div>
  </div>
  <div>
    <%= paginate @comments %>
  </div>